### ISSUE TITLE
Code reloading

### ISSUE THREAD

**Issue by Schniz** [testdouble/cypress-rails#37]
Hey!

First of all, I'd like to say thanks. This project made installing cypress in a pet project a really fast experience! So thanks for your hard work. 

For some reason, when running `rake cypress:open` it seems that my application code doesn't get reloaded on changes. It makes TDDing harder.

I'm not entirely sure if that's something that is specific to my app or not though. Maybe there's a config I'm missing?

**Comment by searls** [comment]
Thanks for pointing this out. I had forgotten to document the setting you need. Added to the [README](https://github.com/testdouble/cypress-rails#configuring-rails) that you want to set `config.cache_classes = false` in your test environment config file.

Fixed by: https://github.com/testdouble/cypress-rails/commit/2299a2246053f721ccc7c4a0bc665d1de2e69fc4

**Comment by Schniz** [comment]
Thanks! 😃
